name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write # Required for pushing to GHCR
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and tag Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ github.sha::8 }} .
          docker tag ghcr.io/${{ github.repository }}:${{ github.sha::8 }} ghcr.io/${{ github.repository }}:latest

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.sha::8 }}
          docker push ghcr.io/${{ github.repository }}:latest

      - name: Logout from GHCR
        if: always()
        run: docker logout ghcr.io
